package generator

import (
	"fmt"
	"sort"
	"strings"
)

func (g *generator) render() []byte {
	var out strings.Builder
	out.WriteString("// Code generated by openapi2proto. DO NOT EDIT.\n")
	out.WriteString(fmt.Sprintf("// Source: %s\n\n", g.sourceName))
	out.WriteString("syntax = \"proto3\";\n\n")
	out.WriteString(fmt.Sprintf("package %s;\n\n", g.cfg.PackageName))
	out.WriteString(fmt.Sprintf("option go_package = %q;\n\n", g.cfg.GoPackage))

	if len(g.imports) > 0 {
		imports := make([]string, 0, len(g.imports))
		for path := range g.imports {
			imports = append(imports, path)
		}
		sort.Strings(imports)
		for _, path := range imports {
			out.WriteString(fmt.Sprintf("import %q;\n", path))
		}
		out.WriteString("\n")
	}

	for _, name := range g.messageOrder {
		renderMessage(&out, g.messages[name])
		out.WriteString("\n")
	}
	for _, name := range g.serviceOrder {
		renderService(&out, g.services[name], g.cfg.PackageName)
		out.WriteString("\n")
	}
	return []byte(out.String())
}

func renderMessage(out *strings.Builder, msg *messageDef) {
	writeComment(out, msg.Comment, 0)
	out.WriteString(fmt.Sprintf("message %s {\n", msg.Name))
	if len(msg.Fields) == 0 {
		out.WriteString("}\n")
		return
	}
	for _, field := range msg.Fields {
		writeComment(out, field.Comment, 1)
		out.WriteString("  ")
		if field.MapValue != "" {
			out.WriteString(fmt.Sprintf("map<string, %s> %s = %d;\n", field.MapValue, field.Name, field.Number))
			continue
		}
		if field.Repeated {
			out.WriteString("repeated ")
		}
		out.WriteString(fmt.Sprintf("%s %s = %d;\n", field.Type, field.Name, field.Number))
	}
	out.WriteString("}\n")
}

func renderService(out *strings.Builder, svc *serviceDef, pkg string) {
	writeComment(out, svc.Comment, 0)
	out.WriteString(fmt.Sprintf("service %s {\n", svc.Name))
	for _, method := range svc.Methods {
		writeComment(out, method.Comment, 1)
		// Fully-qualify the request/response message types with a leading
		// ".package." prefix. Proto name resolution searches enclosing scopes
		// first, so an RPC whose method name collides with a top-level message
		// name (e.g. a "GetSslCertificateRequest" operation alongside a
		// "GetSslCertificate" operation, which both want the message
		// "GetSslCertificateRequest") would otherwise resolve the bare type to
		// the sibling method and fail with "not a message type". The absolute
		// reference sidesteps that collision.
		out.WriteString(fmt.Sprintf("  rpc %s(%s) returns (%s)",
			method.Name,
			qualifyType(method.RequestType, pkg),
			qualifyType(method.ResponseType, pkg)))
		if method.HTTP == nil {
			out.WriteString(";\n")
			continue
		}
		out.WriteString(" {\n")
		out.WriteString("    option (.google.api.http) = {\n")
		switch method.HTTP.Method {
		case "GET", "POST", "PUT", "PATCH", "DELETE":
			out.WriteString(fmt.Sprintf("      %s: %q\n", strings.ToLower(method.HTTP.Method), method.HTTP.Path))
		default:
			out.WriteString("      custom {\n")
			out.WriteString(fmt.Sprintf("        kind: %q\n", method.HTTP.Method))
			out.WriteString(fmt.Sprintf("        path: %q\n", method.HTTP.Path))
			out.WriteString("      }\n")
		}
		if method.HTTP.Body != "" {
			out.WriteString(fmt.Sprintf("      body: %q\n", method.HTTP.Body))
		}
		if method.HTTP.ResponseBody != "" {
			out.WriteString(fmt.Sprintf("      response_body: %q\n", method.HTTP.ResponseBody))
		}
		out.WriteString("    };\n")
		out.WriteString("  }\n")
	}
	out.WriteString("}\n")
}

// qualifyType returns an absolute (leading-dot) reference to a locally
// generated message type so proto name resolution cannot shadow it with a
// sibling method name. Already-qualified names (containing a ".", e.g.
// google.protobuf.Empty, or already absolute) are returned unchanged.
func qualifyType(typeName, pkg string) string {
	if pkg == "" || strings.Contains(typeName, ".") {
		return typeName
	}
	return "." + pkg + "." + typeName
}

func writeComment(out *strings.Builder, comment string, indent int) {
	comment = strings.TrimSpace(comment)
	if comment == "" {
		return
	}
	prefix := strings.Repeat("  ", indent) + "// "
	for _, line := range strings.Split(comment, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		out.WriteString(prefix)
		out.WriteString(line)
		out.WriteString("\n")
	}
}
