package generator

import (
	"fmt"
	"sort"
	"strings"
)

// ServerEntry describes one generated service package for the generic gRPC
// entrypoint produced by GenerateServerMain. BaseURL is the REST base the
// service's runtime client talks to (it may be overridden at run time).
type ServerEntry struct {
	API     string // API name, e.g. "compute"
	Version string // API version, e.g. "v1"
	BaseURL string // REST base URL (no trailing slash), e.g. "https://compute.googleapis.com/compute/v1"
	Import  string // full Go import path of the service package
	Alias   string // unique import alias for the package
}

// GenerateServerMain produces a single generic `main.go` that can serve any one
// of the given service packages over gRPC. The API to serve is selected at run
// time with -api/-version; the package's RegisterAll hook is invoked against a
// runtime.Client built from the (overridable) base URL and a bearer token.
//
// The entries' import paths are blank/aliased into one binary, so the resulting
// program contains every service but serves exactly one per invocation.
func GenerateServerMain(goModule string, entries []ServerEntry) []byte {
	sorted := append([]ServerEntry(nil), entries...)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].API != sorted[j].API {
			return sorted[i].API < sorted[j].API
		}
		return sorted[i].Version < sorted[j].Version
	})

	var b strings.Builder
	b.WriteString("// Code generated by openapi2proto. DO NOT EDIT.\n")
	b.WriteString("// Generic gRPC entrypoint: serves one selected API over gRPC, bridging to REST.\n\n")
	b.WriteString("package main\n\n")

	b.WriteString("import (\n")
	b.WriteString("\t\"flag\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"log\"\n")
	b.WriteString("\t\"net\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\t\"sort\"\n\n")
	b.WriteString("\t\"google.golang.org/grpc\"\n\n")
	b.WriteString("\t\"github.com/accretional/openapi2proto/runtime\"\n")
	for _, e := range sorted {
		b.WriteString(fmt.Sprintf("\t%s %q\n", e.Alias, e.Import))
	}
	b.WriteString(")\n\n")

	// Registry entry type + table.
	b.WriteString("type apiEntry struct {\n")
	b.WriteString("\tbaseURL  string\n")
	b.WriteString("\tregister func(*grpc.Server, *runtime.Client)\n")
	b.WriteString("}\n\n")

	b.WriteString("var registry = map[string]apiEntry{\n")
	for _, e := range sorted {
		key := e.API + "/" + e.Version
		b.WriteString(fmt.Sprintf("\t%q: {baseURL: %q, register: %s.RegisterAll},\n", key, e.BaseURL, e.Alias))
	}
	b.WriteString("}\n\n")

	// main()
	b.WriteString("func main() {\n")
	b.WriteString("\tapi := flag.String(\"api\", \"\", \"API name to serve (e.g. compute)\")\n")
	b.WriteString("\tversion := flag.String(\"version\", \"\", \"API version to serve (e.g. v1)\")\n")
	b.WriteString("\taddr := flag.String(\"addr\", \":50051\", \"gRPC listen address\")\n")
	b.WriteString("\tbaseURL := flag.String(\"base_url\", \"\", \"override the API base URL\")\n")
	b.WriteString("\ttokenFlag := flag.String(\"token\", \"\", \"bearer token (falls back to $GOOGLE_API_TOKEN)\")\n")
	b.WriteString("\tlist := flag.Bool(\"list\", false, \"list available api/version keys and exit\")\n")
	b.WriteString("\tflag.Parse()\n\n")

	b.WriteString("\tif *list {\n")
	b.WriteString("\t\tkeys := make([]string, 0, len(registry))\n")
	b.WriteString("\t\tfor k := range registry {\n")
	b.WriteString("\t\t\tkeys = append(keys, k)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tsort.Strings(keys)\n")
	b.WriteString("\t\tfor _, k := range keys {\n")
	b.WriteString("\t\t\tfmt.Println(k)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\treturn\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\tif *api == \"\" || *version == \"\" {\n")
	b.WriteString("\t\tlog.Fatalf(\"-api and -version are required (use -list to see options)\")\n")
	b.WriteString("\t}\n")
	b.WriteString("\tentry, ok := registry[*api+\"/\"+*version]\n")
	b.WriteString("\tif !ok {\n")
	b.WriteString("\t\tlog.Fatalf(\"unknown api %q version %q (use -list to see options)\", *api, *version)\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\tbase := entry.baseURL\n")
	b.WriteString("\tif *baseURL != \"\" {\n")
	b.WriteString("\t\tbase = *baseURL\n")
	b.WriteString("\t}\n")
	b.WriteString("\ttoken := *tokenFlag\n")
	b.WriteString("\tif token == \"\" {\n")
	b.WriteString("\t\ttoken = os.Getenv(\"GOOGLE_API_TOKEN\")\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\tclient := runtime.New(base, token)\n")
	b.WriteString("\tsrv := grpc.NewServer()\n")
	b.WriteString("\tentry.register(srv, client)\n\n")

	b.WriteString("\tlis, err := net.Listen(\"tcp\", *addr)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tlog.Fatalf(\"listen %s: %v\", *addr, err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tlog.Printf(\"serving %s/%s on %s -> %s\", *api, *version, *addr, base)\n")
	b.WriteString("\tif err := srv.Serve(lis); err != nil {\n")
	b.WriteString("\t\tlog.Fatalf(\"serve: %v\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	return []byte(b.String())
}
