package generator

import (
	"fmt"
	"regexp"
	"strings"
)

var pathParamRE = regexp.MustCompile(`\{([^}]+)\}`)

// GenerateGoService produces a Go source file that implements gRPC service
// handlers bridging to the REST API. goModule is the Go module path of the
// target project (e.g. "github.com/accretional/proto-cloudflare") and pbSubPath
// is the import sub-path where protoc wrote the Go types (e.g. "pb/cloudflare/zones").
func (g *generator) renderGoService(goModule, pbSubPath string) []byte {
	if len(g.serviceOrder) == 0 {
		return nil
	}

	// Derive package name from the go_package alias (part after ";").
	pkgAlias := ""
	if idx := strings.Index(g.cfg.GoPackage, ";"); idx >= 0 {
		pkgAlias = g.cfg.GoPackage[idx+1:]
	}
	if pkgAlias == "" {
		pkgAlias = lastPackageSegment(g.cfg.PackageName)
		pkgAlias = strings.ReplaceAll(pkgAlias, "_", "")
		pkgAlias = strings.ReplaceAll(pkgAlias, ".", "")
	}

	pbImport := goModule + "/" + pbSubPath

	// Track which imports are actually needed.
	needsFmt := false
	needsStrconv := false
	needsURL := false
	needsGRPC := len(g.serviceOrder) > 0

	// Pre-scan methods to determine imports.
	for _, svcName := range g.serviceOrder {
		svc := g.services[svcName]
		for _, rpc := range svc.Methods {
			if rpc.HTTP == nil {
				continue
			}
			if pathParamRE.MatchString(rpc.HTTP.Path) {
				needsURL = true
			}
			reqMsg := g.messages[rpc.RequestType]
			if reqMsg != nil {
				pathSet := pathParamSet(rpc.HTTP.Path)
				for _, f := range reqMsg.Fields {
					if f.Name == rpc.HTTP.Body {
						continue
					}
					if pathSet[f.Name] {
						if f.Type != "string" {
							needsStrconv = true
						}
						needsURL = true
						continue
					}
					if f.Type == "int32" || f.Type == "int64" {
						needsStrconv = true
					} else if f.Type == "double" || f.Type == "float" {
						needsStrconv = true
					}
				}
			}
			_ = needsFmt
		}
	}

	var out strings.Builder
	out.WriteString("// Code generated by openapi2proto. DO NOT EDIT.\n")
	out.WriteString(fmt.Sprintf("// Source: %s\n\n", g.sourceName))
	out.WriteString(fmt.Sprintf("package %s\n\n", pkgAlias))
	out.WriteString("import (\n")
	out.WriteString("\t\"context\"\n")
	if needsStrconv {
		out.WriteString("\t\"strconv\"\n")
	}
	if needsURL {
		out.WriteString("\tneturl \"net/url\"\n")
	}
	out.WriteString("\n")
	out.WriteString(fmt.Sprintf("\tpb %q\n", pbImport))
	out.WriteString("\t\"github.com/accretional/openapi2proto/runtime\"\n")
	if needsGRPC {
		out.WriteString("\t\"google.golang.org/grpc\"\n")
	}
	out.WriteString(")\n\n")

	// One server struct + constructor + Register per service.
	for _, svcName := range g.serviceOrder {
		svc := g.services[svcName]
		g.renderGoServiceImpl(&out, svc, pkgAlias, needsURL, needsStrconv)
	}

	return []byte(out.String())
}

func (g *generator) renderGoServiceImpl(out *strings.Builder, svc *serviceDef, pkgAlias string, needsURL, needsStrconv bool) {
	structName := svc.Name + "Server"
	unimplName := "pb.Unimplemented" + svc.Name + "Server"

	out.WriteString(fmt.Sprintf("// %s implements %s over REST.\n", structName, svc.Name))
	out.WriteString(fmt.Sprintf("type %s struct {\n", structName))
	out.WriteString(fmt.Sprintf("\t%s\n", unimplName))
	out.WriteString("\tclient *runtime.Client\n")
	out.WriteString("}\n\n")

	out.WriteString(fmt.Sprintf("// New%s constructs a %s.\n", structName, structName))
	out.WriteString(fmt.Sprintf("func New%s(client *runtime.Client) *%s {\n", structName, structName))
	out.WriteString(fmt.Sprintf("\treturn &%s{client: client}\n", structName))
	out.WriteString("}\n\n")

	out.WriteString(fmt.Sprintf("// Register wires %s into the gRPC server.\n", structName))
	out.WriteString(fmt.Sprintf("func (s *%s) Register(srv *grpc.Server) {\n", structName))
	out.WriteString(fmt.Sprintf("\tpb.Register%sServer(srv, s)\n", svc.Name))
	out.WriteString("}\n\n")

	for _, rpc := range svc.Methods {
		g.renderGoMethod(out, svc, rpc, structName, pkgAlias, needsURL, needsStrconv)
	}
}

func (g *generator) renderGoMethod(out *strings.Builder, svc *serviceDef, rpc *rpcDef, structName, pkgAlias string, needsURL, needsStrconv bool) {
	reqType := "pb." + rpc.RequestType
	respType := "pb." + rpc.ResponseType

	out.WriteString(fmt.Sprintf("func (s *%s) %s(ctx context.Context, req *%s) (*%s, error) {\n",
		structName, rpc.Name, reqType, respType))

	if rpc.HTTP == nil {
		out.WriteString(fmt.Sprintf("\treturn nil, nil\n}\n\n"))
		return
	}

	// Declare path param local variables, then build path expression using those vars.
	pathParams := pathParamRE.FindAllStringSubmatch(rpc.HTTP.Path, -1)
	for _, m := range pathParams {
		fieldName := m[1]
		getter := "Get" + toCamel(fieldName)
		out.WriteString(fmt.Sprintf("\t%s := req.%s()\n", fieldName, getter))
	}
	pathExpr := buildPathExprFromVars(rpc.HTTP.Path, g.messages[rpc.RequestType])

	// Query params.
	reqMsg := g.messages[rpc.RequestType]
	pathSet := pathParamSet(rpc.HTTP.Path)
	var queryFields []*fieldDef
	if reqMsg != nil {
		for _, f := range reqMsg.Fields {
			if f.Name == rpc.HTTP.Body {
				continue
			}
			if pathSet[f.Name] {
				continue
			}
			queryFields = append(queryFields, f)
		}
	}

	if len(queryFields) > 0 {
		out.WriteString("\tq := neturl.Values{}\n")
		for _, f := range queryFields {
			renderQuerySetter(out, f)
		}
	}

	// Body.
	hasBody := rpc.HTTP.Body != ""
	if hasBody {
		out.WriteString(fmt.Sprintf("\tbodyBytes, err := runtime.MarshalBody(req.Get%s())\n", toCamel(rpc.HTTP.Body)))
		out.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	}

	// HTTP call.
	qArg := "nil"
	if len(queryFields) > 0 {
		qArg = "q"
	}
	bodyArg := "nil"
	if hasBody {
		bodyArg = "bodyBytes"
	}
	out.WriteString(fmt.Sprintf("\tdata, httpStatus, err := s.client.Do(ctx, %q, %s, %s, %s)\n",
		rpc.HTTP.Method, pathExpr, qArg, bodyArg))
	out.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")

	// Response.
	out.WriteString(fmt.Sprintf("\tresp := &pb.%s{HttpStatusCode: int32(httpStatus)}\n", rpc.ResponseType))
	out.WriteString("\tif httpStatus >= 400 {\n")
	out.WriteString("\t\treturn resp, runtime.StatusError(data, httpStatus)\n")
	out.WriteString("\t}\n")

	// Find response body field type.
	respMsg := g.messages[rpc.ResponseType]
	if respMsg != nil {
		bodyField := findField(respMsg, "body")
		if bodyField != nil && isMessageType(bodyField.Type) {
			out.WriteString(fmt.Sprintf("\tresp.Body = &pb.%s{}\n", bodyField.Type))
			out.WriteString("\tif err := runtime.Unmarshal(data, resp.Body); err != nil {\n")
			out.WriteString("\t\treturn nil, err\n\t}\n")
		}
	}

	out.WriteString("\treturn resp, nil\n}\n\n")

	_ = needsURL
	_ = needsStrconv
}

// buildPathExprFromVars converts a path template like /zones/{zone_id}/records/{id}
// into a Go string concatenation expression that references the already-declared local vars.
func buildPathExprFromVars(pathTemplate string, reqMsg *messageDef) string {
	matches := pathParamRE.FindAllStringIndex(pathTemplate, -1)
	if len(matches) == 0 {
		return fmt.Sprintf("%q", pathTemplate)
	}

	var parts []string
	prev := 0
	for _, loc := range matches {
		start, end := loc[0], loc[1]
		if start > prev {
			parts = append(parts, fmt.Sprintf("%q", pathTemplate[prev:start]))
		}
		fieldName := pathTemplate[start+1 : end-1]
		fd := findField(reqMsg, fieldName)
		if fd != nil && fd.Type != "string" {
			switch fd.Type {
			case "int32":
				parts = append(parts, fmt.Sprintf("strconv.FormatInt(int64(%s), 10)", fieldName))
			case "int64":
				parts = append(parts, fmt.Sprintf("strconv.FormatInt(%s, 10)", fieldName))
			case "bool":
				parts = append(parts, fmt.Sprintf("strconv.FormatBool(%s)", fieldName))
			default:
				parts = append(parts, fieldName)
			}
		} else {
			parts = append(parts, fmt.Sprintf("neturl.PathEscape(%s)", fieldName))
		}
		prev = end
	}
	if prev < len(pathTemplate) {
		parts = append(parts, fmt.Sprintf("%q", pathTemplate[prev:]))
	}
	return strings.Join(parts, "+")
}

func renderQuerySetter(out *strings.Builder, f *fieldDef) {
	getter := "Get" + toCamel(f.Name)
	// Use original field name as query key (proto name = snake_case of API param name).
	key := f.Name
	switch f.Type {
	case "string":
		out.WriteString(fmt.Sprintf("\tif v := req.%s(); v != \"\" { q.Set(%q, v) }\n", getter, key))
	case "int32":
		out.WriteString(fmt.Sprintf("\tif v := req.%s(); v != 0 { q.Set(%q, strconv.FormatInt(int64(v), 10)) }\n", getter, key))
	case "int64":
		out.WriteString(fmt.Sprintf("\tif v := req.%s(); v != 0 { q.Set(%q, strconv.FormatInt(v, 10)) }\n", getter, key))
	case "bool":
		out.WriteString(fmt.Sprintf("\tif req.%s() { q.Set(%q, \"true\") }\n", getter, key))
	case "double":
		out.WriteString(fmt.Sprintf("\tif v := req.%s(); v != 0 { q.Set(%q, strconv.FormatFloat(float64(v), 'f', -1, 64)) }\n", getter, key))
	case "float":
		out.WriteString(fmt.Sprintf("\tif v := req.%s(); v != 0 { q.Set(%q, strconv.FormatFloat(float64(v), 'f', -1, 32)) }\n", getter, key))
	default:
		// repeated or message — skip for query params
	}
}

func pathParamSet(pathTemplate string) map[string]bool {
	s := make(map[string]bool)
	for _, m := range pathParamRE.FindAllStringSubmatch(pathTemplate, -1) {
		s[m[1]] = true
	}
	return s
}

func findField(msg *messageDef, name string) *fieldDef {
	if msg == nil {
		return nil
	}
	for _, f := range msg.Fields {
		if f.Name == name {
			return f
		}
	}
	return nil
}

// isMessageType returns true for generated message type names (PascalCase,
// no dots, no lowercase proto primitives).
func isMessageType(t string) bool {
	if t == "" {
		return false
	}
	// Proto primitives are all lowercase; well-known types have dots.
	if strings.Contains(t, ".") {
		// google.protobuf.Struct, google.api.HttpBody — treat as messages.
		return true
	}
	primitives := map[string]bool{
		"string": true, "bool": true, "int32": true, "int64": true,
		"uint32": true, "uint64": true, "float": true, "double": true,
		"bytes": true, "sint32": true, "sint64": true, "fixed32": true,
		"fixed64": true, "sfixed32": true, "sfixed64": true,
	}
	return !primitives[t]
}
