package generator

import (
	"fmt"
	"regexp"
	"strings"
)

var pathParamRE = regexp.MustCompile(`\{([^}]+)\}`)

// reservedLocalNames are identifiers that a path-parameter local variable must
// not shadow: Go keywords (which would be a syntax error, e.g. a param named
// "type" or "range") plus the fixed identifiers the service template itself
// declares in the same scope (which would cause redeclaration/shadowing, e.g.
// a param named "req" or "q"). Any path param whose name collides gets a "_"
// suffix.
var reservedLocalNames = map[string]bool{
	// Go keywords.
	"break": true, "case": true, "chan": true, "const": true, "continue": true,
	"default": true, "defer": true, "else": true, "fallthrough": true, "for": true,
	"func": true, "go": true, "goto": true, "if": true, "import": true,
	"interface": true, "map": true, "package": true, "range": true, "return": true,
	"select": true, "struct": true, "switch": true, "type": true, "var": true,
	// Template-declared identifiers and imported package aliases.
	"ctx": true, "req": true, "s": true, "q": true, "err": true, "resp": true,
	"data": true, "httpStatus": true, "bodyBytes": true, "v": true,
	"neturl": true, "strconv": true, "runtime": true, "context": true,
	"grpc": true, "pb": true,
}

// goLocalName returns a Go identifier safe to use as a path-parameter local
// variable, escaping names that would collide with keywords or the service
// template's own variables.
func goLocalName(fieldName string) string {
	if reservedLocalNames[fieldName] {
		return fieldName + "_"
	}
	return fieldName
}

// protoNameToGoName applies protoc-gen-go's rule of capitalizing lowercase
// letters that immediately follow a digit. E.g. "Pfx2as" → "Pfx2As".
func protoNameToGoName(name string) string {
	if !strings.ContainsAny(name, "0123456789") {
		return name
	}
	b := strings.Builder{}
	b.Grow(len(name))
	for i := 0; i < len(name); i++ {
		c := name[i]
		if i > 0 && name[i-1] >= '0' && name[i-1] <= '9' && c >= 'a' && c <= 'z' {
			b.WriteByte(c - 32)
		} else {
			b.WriteByte(c)
		}
	}
	return b.String()
}

// GenerateGoService produces a Go source file that implements gRPC service
// handlers bridging to the REST API. goModule is the Go module path of the
// target project (e.g. "github.com/accretional/proto-cloudflare") and pbSubPath
// is the import sub-path where protoc wrote the Go types (e.g. "pb/cloudflare/zones").
func (g *generator) renderGoService(goModule, pbSubPath, runtimeImport string) []byte {
	if len(g.serviceOrder) == 0 {
		return nil
	}

	// Derive package name from the go_package alias (part after ";").
	pkgAlias := ""
	if idx := strings.Index(g.cfg.GoPackage, ";"); idx >= 0 {
		pkgAlias = g.cfg.GoPackage[idx+1:]
	}
	if pkgAlias == "" {
		pkgAlias = lastPackageSegment(g.cfg.PackageName)
		pkgAlias = strings.ReplaceAll(pkgAlias, "_", "")
		pkgAlias = strings.ReplaceAll(pkgAlias, ".", "")
	}

	pbImport := goModule + "/" + pbSubPath

	// Track which imports are actually needed.
	needsStrconv := false
	needsURL := false
	needsGRPC := len(g.serviceOrder) > 0

	// Pre-scan methods to determine imports.
	for _, svcName := range g.serviceOrder {
		svc := g.services[svcName]
		for _, rpc := range svc.Methods {
			if rpc.HTTP == nil {
				continue
			}
			reqMsg := g.messages[rpc.RequestType]
			if reqMsg != nil {
				pathSet := pathParamSet(rpc.HTTP.Path)
				for _, f := range reqMsg.Fields {
					if f.Name == rpc.HTTP.Body {
						continue
					}
					if pathSet[f.Name] {
						if isMessageType(f.Type) {
							if g.messageInnerValueType(f.Type) != "string" {
								needsStrconv = true
							}
						} else if f.Type == "float" || f.Type == "double" {
							needsStrconv = true
						} else if f.Type != "string" {
							needsStrconv = true
						}
						// Path params escape via runtime.EscapePath, not net/url.
						continue
					}
					// Query params.
					if f.Type == "int32" || f.Type == "int64" || f.Type == "double" || f.Type == "float" {
						needsStrconv = true
					}
					if len(f.Type) > 0 {
						needsURL = true
					}
				}
			}
		}
	}

	var out strings.Builder
	out.WriteString("// Code generated by openapi2proto. DO NOT EDIT.\n")
	out.WriteString(fmt.Sprintf("// Source: %s\n\n", g.sourceName))
	out.WriteString(fmt.Sprintf("package %s\n\n", pkgAlias))
	out.WriteString("import (\n")
	out.WriteString("\t\"context\"\n")
	if needsStrconv {
		out.WriteString("\t\"strconv\"\n")
	}
	if needsURL {
		out.WriteString("\tneturl \"net/url\"\n")
	}
	out.WriteString("\n")
	out.WriteString(fmt.Sprintf("\tpb %q\n", pbImport))
	out.WriteString(fmt.Sprintf("\t%q\n", runtimeImport))
	if needsGRPC {
		out.WriteString("\t\"google.golang.org/grpc\"\n")
	}
	out.WriteString(")\n\n")

	// One server struct + constructor + Register per service.
	for _, svcName := range g.serviceOrder {
		svc := g.services[svcName]
		g.renderGoServiceImpl(&out, svc, pkgAlias, needsURL, needsStrconv)
	}

	// RegisterAll wires every service in this package onto a gRPC server,
	// giving entrypoints a uniform hook regardless of how many services the
	// spec produced.
	out.WriteString("// RegisterAll registers every service in this package on srv using client.\n")
	out.WriteString("func RegisterAll(srv *grpc.Server, client *runtime.Client) {\n")
	for _, svcName := range g.serviceOrder {
		goSvcName := protoNameToGoName(g.services[svcName].Name)
		out.WriteString(fmt.Sprintf("\tNew%sServer(client).Register(srv)\n", goSvcName))
	}
	out.WriteString("}\n")

	return []byte(out.String())
}

// messageInnerValueType returns the type of the "value" field inside a wrapper
// message (e.g. IamAccountIdentifier → "string", IntelAsn → "int64").
// Returns "string" if the message or field is not found.
func (g *generator) messageInnerValueType(msgName string) string {
	inner := g.messages[msgName]
	if inner == nil {
		return "string"
	}
	fd := findField(inner, "value")
	if fd == nil {
		return "string"
	}
	return fd.Type
}

func (g *generator) renderGoServiceImpl(out *strings.Builder, svc *serviceDef, pkgAlias string, needsURL, needsStrconv bool) {
	goSvcName := protoNameToGoName(svc.Name)
	structName := goSvcName + "Server"
	unimplName := "pb.Unimplemented" + goSvcName + "Server"

	out.WriteString(fmt.Sprintf("// %s implements %s over REST.\n", structName, goSvcName))
	out.WriteString(fmt.Sprintf("type %s struct {\n", structName))
	out.WriteString(fmt.Sprintf("\t%s\n", unimplName))
	out.WriteString("\tclient *runtime.Client\n")
	out.WriteString("}\n\n")

	out.WriteString(fmt.Sprintf("// New%s constructs a %s.\n", structName, structName))
	out.WriteString(fmt.Sprintf("func New%s(client *runtime.Client) *%s {\n", structName, structName))
	out.WriteString(fmt.Sprintf("\treturn &%s{client: client}\n", structName))
	out.WriteString("}\n\n")

	out.WriteString(fmt.Sprintf("// Register wires %s into the gRPC server.\n", structName))
	out.WriteString(fmt.Sprintf("func (s *%s) Register(srv *grpc.Server) {\n", structName))
	out.WriteString(fmt.Sprintf("\tpb.Register%sServer(srv, s)\n", goSvcName))
	out.WriteString("}\n\n")

	for _, rpc := range svc.Methods {
		g.renderGoMethod(out, svc, rpc, structName, pkgAlias, needsURL, needsStrconv)
	}
}

func (g *generator) renderGoMethod(out *strings.Builder, svc *serviceDef, rpc *rpcDef, structName, pkgAlias string, needsURL, needsStrconv bool) {
	goReqType := protoNameToGoName(rpc.RequestType)
	goRespType := protoNameToGoName(rpc.ResponseType)
	goRpcName := protoNameToGoName(rpc.Name)
	reqType := "pb." + goReqType
	respType := "pb." + goRespType

	out.WriteString(fmt.Sprintf("func (s *%s) %s(ctx context.Context, req *%s) (*%s, error) {\n",
		structName, goRpcName, reqType, respType))

	if rpc.HTTP == nil {
		out.WriteString("\treturn nil, nil\n}\n\n")
		return
	}

	// Declare path param local variables (always string after conversion).
	// Track declared vars to avoid redeclaring duplicates.
	pathParams := pathParamRE.FindAllStringSubmatch(rpc.HTTP.Path, -1)
	reqMsg := g.messages[rpc.RequestType]
	declared := make(map[string]bool)
	for _, m := range pathParams {
		fieldName := m[1]
		if declared[fieldName] {
			continue
		}
		declared[fieldName] = true
		varName := goLocalName(fieldName)
		getter := protoNameToGoName("Get" + toCamel(fieldName))
		fd := findField(reqMsg, fieldName)
		if fd != nil && isMessageType(fd.Type) {
			// Message wrapper: extract inner value and convert to string.
			inner := g.messageInnerValueType(fd.Type)
			switch inner {
			case "int32":
				out.WriteString(fmt.Sprintf("\t%s := strconv.FormatInt(int64(req.%s().GetValue()), 10)\n", varName, getter))
			case "int64":
				out.WriteString(fmt.Sprintf("\t%s := strconv.FormatInt(req.%s().GetValue(), 10)\n", varName, getter))
			case "float":
				out.WriteString(fmt.Sprintf("\t%s := strconv.FormatFloat(float64(req.%s().GetValue()), 'f', -1, 32)\n", varName, getter))
			case "double":
				out.WriteString(fmt.Sprintf("\t%s := strconv.FormatFloat(req.%s().GetValue(), 'f', -1, 64)\n", varName, getter))
			default: // string or unknown
				out.WriteString(fmt.Sprintf("\t%s := req.%s().GetValue()\n", varName, getter))
			}
		} else if fd != nil && fd.Type == "float" {
			out.WriteString(fmt.Sprintf("\t%s := strconv.FormatFloat(float64(req.%s()), 'f', -1, 32)\n", varName, getter))
		} else if fd != nil && fd.Type == "double" {
			out.WriteString(fmt.Sprintf("\t%s := strconv.FormatFloat(req.%s(), 'f', -1, 64)\n", varName, getter))
		} else {
			out.WriteString(fmt.Sprintf("\t%s := req.%s()\n", varName, getter))
		}
	}
	pathExpr := buildPathExprFromVars(rpc.HTTP.Path, reqMsg)

	// Query params.
	pathSet := pathParamSet(rpc.HTTP.Path)
	var queryFields []*fieldDef
	if reqMsg != nil {
		for _, f := range reqMsg.Fields {
			if f.Name == rpc.HTTP.Body {
				continue
			}
			if pathSet[f.Name] {
				continue
			}
			queryFields = append(queryFields, f)
		}
	}

	if len(queryFields) > 0 {
		out.WriteString("\tq := neturl.Values{}\n")
		for _, f := range queryFields {
			renderQuerySetter(out, f)
		}
	}

	// Body.
	hasBody := rpc.HTTP.Body != ""
	if hasBody {
		bodyFd := findField(reqMsg, rpc.HTTP.Body)
		useProtoMarshal := bodyFd != nil &&
			isMessageType(bodyFd.Type) &&
			!bodyFd.Repeated &&
			bodyFd.MapValue == "" &&
			!strings.Contains(bodyFd.Type, ".")
		bodyGetter := protoNameToGoName("Get" + toCamel(rpc.HTTP.Body))
		if useProtoMarshal {
			out.WriteString(fmt.Sprintf("\tbodyBytes, err := runtime.MarshalBody(req.%s())\n", bodyGetter))
		} else {
			out.WriteString(fmt.Sprintf("\tbodyBytes, err := runtime.MarshalBodyAny(req.%s())\n", bodyGetter))
		}
		out.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	}

	// HTTP call.
	qArg := "nil"
	if len(queryFields) > 0 {
		qArg = "q"
	}
	bodyArg := "nil"
	if hasBody {
		bodyArg = "bodyBytes"
	}
	out.WriteString(fmt.Sprintf("\tdata, httpStatus, err := s.client.Do(ctx, %q, %s, %s, %s)\n",
		rpc.HTTP.Method, pathExpr, qArg, bodyArg))
	out.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")

	// Response.
	out.WriteString(fmt.Sprintf("\tresp := &pb.%s{HttpStatusCode: int32(httpStatus)}\n", goRespType))
	out.WriteString("\tif httpStatus >= 400 {\n")
	out.WriteString("\t\treturn resp, runtime.StatusError(data, httpStatus)\n")
	out.WriteString("\t}\n")

	// Find response body field type.
	respMsg := g.messages[rpc.ResponseType]
	if respMsg != nil {
		bodyField := findField(respMsg, "body")
		if bodyField != nil {
			isDotted := strings.Contains(bodyField.Type, ".")
			isLocalMsg := isMessageType(bodyField.Type) && !isDotted && bodyField.MapValue == ""
			if isLocalMsg && !bodyField.Repeated {
				// Single local message body: use proto-aware Unmarshal.
				goBodyType := protoNameToGoName(bodyField.Type)
				out.WriteString(fmt.Sprintf("\tresp.Body = &pb.%s{}\n", goBodyType))
				out.WriteString("\tif err := runtime.Unmarshal(data, resp.Body); err != nil {\n")
				out.WriteString("\t\treturn nil, err\n\t}\n")
			} else if !isDotted {
				// Repeated, map, or primitive body: use generic JSON unmarshal.
				out.WriteString("\tif err := runtime.UnmarshalInto(data, &resp.Body); err != nil {\n")
				out.WriteString("\t\treturn nil, err\n\t}\n")
			}
			// Dotted types (google.api.HttpBody etc.) are left empty (no unmarshal).
		}
	}

	out.WriteString("\treturn resp, nil\n}\n\n")

	_ = needsURL
	_ = needsStrconv
}

// buildPathExprFromVars converts a path template like /zones/{zone_id}/records/{id}
// into a Go string concatenation expression. All path param variables are already
// strings at this point (converted in the declaration).
func buildPathExprFromVars(pathTemplate string, reqMsg *messageDef) string {
	matches := pathParamRE.FindAllStringIndex(pathTemplate, -1)
	if len(matches) == 0 {
		return fmt.Sprintf("%q", pathTemplate)
	}

	var parts []string
	prev := 0
	for _, loc := range matches {
		start, end := loc[0], loc[1]
		if start > prev {
			parts = append(parts, fmt.Sprintf("%q", pathTemplate[prev:start]))
		}
		fieldName := pathTemplate[start+1 : end-1]
		varName := goLocalName(fieldName)
		fd := findField(reqMsg, fieldName)
		if fd != nil && !isMessageType(fd.Type) && fd.Type != "string" &&
			fd.Type != "float" && fd.Type != "double" {
			// Primitive non-string, non-float types: variable holds the raw value.
			switch fd.Type {
			case "int32":
				parts = append(parts, fmt.Sprintf("strconv.FormatInt(int64(%s), 10)", varName))
			case "int64":
				parts = append(parts, fmt.Sprintf("strconv.FormatInt(%s, 10)", varName))
			case "bool":
				parts = append(parts, fmt.Sprintf("strconv.FormatBool(%s)", varName))
			default:
				parts = append(parts, varName)
			}
		} else {
			// string, float/double (already string in declaration), and message types
			// (GetValue() already called) all use PathEscape.
			parts = append(parts, fmt.Sprintf("runtime.EscapePath(%s)", varName))
		}
		prev = end
	}
	if prev < len(pathTemplate) {
		parts = append(parts, fmt.Sprintf("%q", pathTemplate[prev:]))
	}
	return strings.Join(parts, "+")
}

func renderQuerySetter(out *strings.Builder, f *fieldDef) {
	getter := protoNameToGoName("Get" + toCamel(f.Name))
	key := f.Name
	if f.OrigName != "" {
		key = f.OrigName
	}

	if f.Repeated {
		switch f.Type {
		case "string":
			out.WriteString(fmt.Sprintf("\tfor _, s := range req.%s() { q.Add(%q, s) }\n", getter, key))
		case "int32":
			out.WriteString(fmt.Sprintf("\tfor _, n := range req.%s() { q.Add(%q, strconv.FormatInt(int64(n), 10)) }\n", getter, key))
		case "int64":
			out.WriteString(fmt.Sprintf("\tfor _, n := range req.%s() { q.Add(%q, strconv.FormatInt(n, 10)) }\n", getter, key))
		case "bool":
			out.WriteString(fmt.Sprintf("\tfor _, b := range req.%s() { q.Add(%q, strconv.FormatBool(b)) }\n", getter, key))
		case "double":
			out.WriteString(fmt.Sprintf("\tfor _, v := range req.%s() { q.Add(%q, strconv.FormatFloat(v, 'f', -1, 64)) }\n", getter, key))
		case "float":
			out.WriteString(fmt.Sprintf("\tfor _, v := range req.%s() { q.Add(%q, strconv.FormatFloat(float64(v), 'f', -1, 32)) }\n", getter, key))
		// repeated message / other types — skip
		}
		return
	}

	switch f.Type {
	case "string":
		out.WriteString(fmt.Sprintf("\tif v := req.%s(); v != \"\" { q.Set(%q, v) }\n", getter, key))
	case "int32":
		out.WriteString(fmt.Sprintf("\tif v := req.%s(); v != 0 { q.Set(%q, strconv.FormatInt(int64(v), 10)) }\n", getter, key))
	case "int64":
		out.WriteString(fmt.Sprintf("\tif v := req.%s(); v != 0 { q.Set(%q, strconv.FormatInt(v, 10)) }\n", getter, key))
	case "bool":
		out.WriteString(fmt.Sprintf("\tif req.%s() { q.Set(%q, \"true\") }\n", getter, key))
	case "double":
		out.WriteString(fmt.Sprintf("\tif v := req.%s(); v != 0 { q.Set(%q, strconv.FormatFloat(v, 'f', -1, 64)) }\n", getter, key))
	case "float":
		out.WriteString(fmt.Sprintf("\tif v := req.%s(); v != 0 { q.Set(%q, strconv.FormatFloat(float64(v), 'f', -1, 32)) }\n", getter, key))
	default:
		// message or unknown — skip
	}
}

func pathParamSet(pathTemplate string) map[string]bool {
	s := make(map[string]bool)
	for _, m := range pathParamRE.FindAllStringSubmatch(pathTemplate, -1) {
		s[m[1]] = true
	}
	return s
}

func findField(msg *messageDef, name string) *fieldDef {
	if msg == nil {
		return nil
	}
	for _, f := range msg.Fields {
		if f.Name == name {
			return f
		}
	}
	return nil
}

// isMessageType returns true for generated message type names (PascalCase,
// no dots, no lowercase proto primitives).
func isMessageType(t string) bool {
	if t == "" {
		return false
	}
	if strings.Contains(t, ".") {
		return true
	}
	primitives := map[string]bool{
		"string": true, "bool": true, "int32": true, "int64": true,
		"uint32": true, "uint64": true, "float": true, "double": true,
		"bytes": true, "sint32": true, "sint64": true, "fixed32": true,
		"fixed64": true, "sfixed32": true, "sfixed64": true,
	}
	return !primitives[t]
}
