package generator

import (
	"fmt"
	"sort"
	"strings"
)

// ServerEntry describes one generated service package for the generic gRPC
// entrypoint produced by GenerateServerMain. BaseURL is the REST base the
// service's runtime client talks to (it may be overridden at run time).
type ServerEntry struct {
	API     string // API name, e.g. "compute"
	Version string // API version, e.g. "v1"
	BaseURL string // REST base URL (no trailing slash), e.g. "https://compute.googleapis.com/compute/v1"
	Import  string // full Go import path of the service package
	Alias   string // unique import alias for the package
}

// GenerateServerMain produces a single generic `main.go` that can serve any one
// of the given service packages over gRPC. The API to serve is selected at run
// time with -api/-version; the package's RegisterAll hook is invoked against a
// runtime.Client built from the (overridable) base URL and a bearer token.
//
// The entries' import paths are blank/aliased into one binary, so the resulting
// program contains every service but serves exactly one per invocation.
func GenerateServerMain(goModule string, entries []ServerEntry) []byte {
	sorted := append([]ServerEntry(nil), entries...)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].API != sorted[j].API {
			return sorted[i].API < sorted[j].API
		}
		return sorted[i].Version < sorted[j].Version
	})

	var b strings.Builder
	b.WriteString("// Code generated by openapi2proto. DO NOT EDIT.\n")
	b.WriteString("// Generic gRPC entrypoint: serves one selected API over gRPC, bridging to REST.\n\n")
	b.WriteString("package main\n\n")

	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"flag\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"io\"\n")
	b.WriteString("\t\"log\"\n")
	b.WriteString("\t\"net\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\t\"sort\"\n")
	b.WriteString("\t\"strings\"\n\n")
	b.WriteString("\t\"google.golang.org/grpc\"\n")
	b.WriteString("\t\"google.golang.org/grpc/metadata\"\n")
	b.WriteString("\t\"google.golang.org/grpc/reflection\"\n")
	b.WriteString("\t\"google.golang.org/protobuf/encoding/prototext\"\n\n")
	b.WriteString("\t\"github.com/accretional/openapi2proto/runtime\"\n")
	for _, e := range sorted {
		b.WriteString(fmt.Sprintf("\t%s %q\n", e.Alias, e.Import))
	}
	b.WriteString(")\n\n")

	// Auth interceptor: forward a caller-supplied bearer token (gRPC
	// "authorization" metadata) to the upstream API, overriding the server's
	// own token for that request.
	b.WriteString("// tokenInterceptor forwards a caller's \"authorization\" metadata token to the\n")
	b.WriteString("// upstream REST call, so clients may supply their own (more privileged) token\n")
	b.WriteString("// while the server falls back to its configured service-account token.\n")
	b.WriteString("func tokenInterceptor(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (any, error) {\n")
	b.WriteString("\tif md, ok := metadata.FromIncomingContext(ctx); ok {\n")
	b.WriteString("\t\tif vals := md.Get(\"authorization\"); len(vals) > 0 && vals[0] != \"\" {\n")
	b.WriteString("\t\t\tctx = runtime.WithToken(ctx, strings.TrimPrefix(vals[0], \"Bearer \"))\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn handler(ctx, req)\n")
	b.WriteString("}\n\n")

	// Registry entry type + table.
	b.WriteString("type apiEntry struct {\n")
	b.WriteString("\tbaseURL  string\n")
	b.WriteString("\tregister func(*grpc.Server, *runtime.Client)\n")
	b.WriteString("}\n\n")

	b.WriteString("var registry = map[string]apiEntry{\n")
	for _, e := range sorted {
		key := e.API + "/" + e.Version
		b.WriteString(fmt.Sprintf("\t%q: {baseURL: %q, register: %s.RegisterAll},\n", key, e.BaseURL, e.Alias))
	}
	b.WriteString("}\n\n")

	b.WriteString("func listAPIs() {\n")
	b.WriteString("\tkeys := make([]string, 0, len(registry))\n")
	b.WriteString("\tfor k := range registry {\n")
	b.WriteString("\t\tkeys = append(keys, k)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tsort.Strings(keys)\n")
	b.WriteString("\tfor _, k := range keys {\n")
	b.WriteString("\t\tfmt.Println(k)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// readTokenFromStdin returns the bearer token piped on stdin (e.g.
	// `gcloud auth print-access-token ... | server ...`). It returns "" when
	// stdin is a terminal, so the server can also run with only caller-supplied
	// per-request tokens.
	b.WriteString("// readTokenFromStdin reads a bearer token piped on stdin (e.g.\n")
	b.WriteString("// `gcloud auth print-access-token | server --server-config=...`). Returns \"\"\n")
	b.WriteString("// when stdin is a terminal, so the server may instead rely on per-request\n")
	b.WriteString("// caller tokens. Keeping the token off the command line avoids leaking it via\n")
	b.WriteString("// argv or shell history.\n")
	b.WriteString("func readTokenFromStdin() string {\n")
	b.WriteString("\tfi, err := os.Stdin.Stat()\n")
	b.WriteString("\tif err != nil || (fi.Mode()&os.ModeCharDevice) != 0 {\n")
	b.WriteString("\t\treturn \"\" // no pipe/redirect; stdin is a terminal\n")
	b.WriteString("\t}\n")
	b.WriteString("\tb, err := io.ReadAll(os.Stdin)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tlog.Fatalf(\"reading token from stdin: %v\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn strings.TrimSpace(string(b))\n")
	b.WriteString("}\n\n")

	// main()
	b.WriteString("func main() {\n")
	b.WriteString("\tconfigPath := flag.String(\"server-config\", \"\", \"path to textproto server config (runtime.ServerConfig)\")\n")
	b.WriteString("\tlist := flag.Bool(\"list\", false, \"list available api/version keys and exit\")\n")
	b.WriteString("\tflag.Parse()\n\n")

	b.WriteString("\tif *list {\n")
	b.WriteString("\t\tlistAPIs()\n")
	b.WriteString("\t\treturn\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif *configPath == \"\" {\n")
	b.WriteString("\t\tlog.Fatalf(\"--server-config is required (use -list to see available apis)\")\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\traw, err := os.ReadFile(*configPath)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tlog.Fatalf(\"reading config: %v\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tcfg := &runtime.ServerConfig{}\n")
	b.WriteString("\tif err := prototext.Unmarshal(raw, cfg); err != nil {\n")
	b.WriteString("\t\tlog.Fatalf(\"parsing config %s: %v\", *configPath, err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\taddress := cfg.GetAddress()\n")
	b.WriteString("\tif address == \"\" {\n")
	b.WriteString("\t\taddress = \":50051\"\n")
	b.WriteString("\t}\n")
	b.WriteString("\tentry, ok := registry[cfg.GetApi()+\"/\"+cfg.GetVersion()]\n")
	b.WriteString("\tif !ok {\n")
	b.WriteString("\t\tlog.Fatalf(\"unknown api %q version %q (use -list to see options)\", cfg.GetApi(), cfg.GetVersion())\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\tbase := entry.baseURL\n")
	b.WriteString("\tif cfg.GetBaseUrl() != \"\" {\n")
	b.WriteString("\t\tbase = cfg.GetBaseUrl()\n")
	b.WriteString("\t}\n")
	b.WriteString("\t// The server's own identity token is read from stdin, never a flag.\n")
	b.WriteString("\ttoken := readTokenFromStdin()\n\n")

	b.WriteString("\tclient := runtime.New(base, token)\n")
	b.WriteString("\tsrv := grpc.NewServer(grpc.UnaryInterceptor(tokenInterceptor))\n")
	b.WriteString("\tentry.register(srv, client)\n")
	b.WriteString("\treflection.Register(srv) // expose the served API via gRPC reflection\n\n")

	b.WriteString("\tlis, err := net.Listen(\"tcp\", address)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tlog.Fatalf(\"listen %s: %v\", address, err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\thasToken := \"no token (caller-supplied only)\"\n")
	b.WriteString("\tif token != \"\" {\n")
	b.WriteString("\t\thasToken = \"server token from stdin\"\n")
	b.WriteString("\t}\n")
	b.WriteString("\tlog.Printf(\"serving %s/%s on %s -> %s (%s)\", cfg.GetApi(), cfg.GetVersion(), address, base, hasToken)\n")
	b.WriteString("\tif err := srv.Serve(lis); err != nil {\n")
	b.WriteString("\t\tlog.Fatalf(\"serve: %v\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	return []byte(b.String())
}

// GenerateClientMain produces a single generic gRPC client `main.go` that can
// call any RPC of any service in the given packages. It is descriptor-driven:
// the service packages are blank-imported so every proto descriptor registers
// in the global registry, then a method is resolved by its full path, its JSON
// request is unmarshalled into a dynamic message, the RPC is invoked, and the
// response is printed as JSON. No per-RPC code is generated.
func GenerateClientMain(goModule string, entries []ServerEntry) []byte {
	// Unique, sorted service import paths for blank import.
	seen := make(map[string]bool)
	var imports []string
	for _, e := range entries {
		if e.Import != "" && !seen[e.Import] {
			seen[e.Import] = true
			imports = append(imports, e.Import)
		}
	}
	sort.Strings(imports)

	var b strings.Builder
	b.WriteString("// Code generated by openapi2proto. DO NOT EDIT.\n")
	b.WriteString("// Generic gRPC client: calls any RPC of any served API by full method path.\n\n")
	b.WriteString("package main\n\n")

	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"flag\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"log\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\t\"sort\"\n")
	b.WriteString("\t\"strings\"\n")
	b.WriteString("\t\"time\"\n\n")
	b.WriteString("\t\"google.golang.org/grpc\"\n")
	b.WriteString("\t\"google.golang.org/grpc/credentials/insecure\"\n")
	b.WriteString("\t\"google.golang.org/grpc/metadata\"\n")
	b.WriteString("\t\"google.golang.org/protobuf/encoding/protojson\"\n")
	b.WriteString("\t\"google.golang.org/protobuf/reflect/protoreflect\"\n")
	b.WriteString("\t\"google.golang.org/protobuf/reflect/protoregistry\"\n")
	b.WriteString("\t\"google.golang.org/protobuf/types/dynamicpb\"\n\n")
	b.WriteString("\t// Blank imports register every API's proto descriptors so any method\n")
	b.WriteString("\t// can be resolved and invoked dynamically.\n")
	for _, imp := range imports {
		b.WriteString(fmt.Sprintf("\t_ %q\n", imp))
	}
	b.WriteString(")\n\n")

	// listMethods helper.
	b.WriteString("// listMethods prints every \"/package.Service/Method\" path, optionally\n")
	b.WriteString("// filtered by a substring.\n")
	b.WriteString("func listMethods(filter string) {\n")
	b.WriteString("\tvar paths []string\n")
	b.WriteString("\tprotoregistry.GlobalFiles.RangeFiles(func(fd protoreflect.FileDescriptor) bool {\n")
	b.WriteString("\t\tsvcs := fd.Services()\n")
	b.WriteString("\t\tfor i := 0; i < svcs.Len(); i++ {\n")
	b.WriteString("\t\t\tsvc := svcs.Get(i)\n")
	b.WriteString("\t\t\tmethods := svc.Methods()\n")
	b.WriteString("\t\t\tfor j := 0; j < methods.Len(); j++ {\n")
	b.WriteString("\t\t\t\tp := \"/\" + string(svc.FullName()) + \"/\" + string(methods.Get(j).Name())\n")
	b.WriteString("\t\t\t\tif filter == \"\" || strings.Contains(p, filter) {\n")
	b.WriteString("\t\t\t\t\tpaths = append(paths, p)\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\treturn true\n")
	b.WriteString("\t})\n")
	b.WriteString("\tsort.Strings(paths)\n")
	b.WriteString("\tfor _, p := range paths {\n")
	b.WriteString("\t\tfmt.Println(p)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// resolveMethod helper.
	b.WriteString("// resolveMethod looks up a method descriptor from a \"/pkg.Service/Method\" path.\n")
	b.WriteString("func resolveMethod(full string) (protoreflect.MethodDescriptor, error) {\n")
	b.WriteString("\tfull = strings.TrimPrefix(full, \"/\")\n")
	b.WriteString("\tidx := strings.LastIndex(full, \"/\")\n")
	b.WriteString("\tif idx < 0 {\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"method must be /package.Service/Method\")\n")
	b.WriteString("\t}\n")
	b.WriteString("\tsvcName, methodName := full[:idx], full[idx+1:]\n")
	b.WriteString("\td, err := protoregistry.GlobalFiles.FindDescriptorByName(protoreflect.FullName(svcName))\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"service %q: %w\", svcName, err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tsd, ok := d.(protoreflect.ServiceDescriptor)\n")
	b.WriteString("\tif !ok {\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"%q is not a service\", svcName)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tmd := sd.Methods().ByName(protoreflect.Name(methodName))\n")
	b.WriteString("\tif md == nil {\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"method %q not found on %q\", methodName, svcName)\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn md, nil\n")
	b.WriteString("}\n\n")

	// main()
	b.WriteString("func main() {\n")
	b.WriteString("\taddr := flag.String(\"addr\", \"localhost:50051\", \"gRPC server address\")\n")
	b.WriteString("\tmethod := flag.String(\"method\", \"\", \"full method path, e.g. /compute.v1.V1Service/ComputeProjectsGet\")\n")
	b.WriteString("\tdata := flag.String(\"data\", \"{}\", \"request body as JSON\")\n")
	b.WriteString("\tlist := flag.Bool(\"list\", false, \"list available method paths and exit\")\n")
	b.WriteString("\tfilter := flag.String(\"filter\", \"\", \"substring filter for -list\")\n")
	b.WriteString("\ttimeout := flag.Duration(\"timeout\", 30*time.Second, \"request timeout\")\n")
	b.WriteString("\ttoken := flag.String(\"token\", \"\", \"bearer token sent to the server (falls back to $GOOGLE_API_TOKEN)\")\n")
	b.WriteString("\tflag.Parse()\n\n")

	b.WriteString("\tif *list {\n")
	b.WriteString("\t\tlistMethods(*filter)\n")
	b.WriteString("\t\treturn\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif *method == \"\" {\n")
	b.WriteString("\t\tlog.Fatalf(\"-method is required (use -list to see options)\")\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\tmd, err := resolveMethod(*method)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tlog.Fatalf(\"%v\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\treq := dynamicpb.NewMessage(md.Input())\n")
	b.WriteString("\tresp := dynamicpb.NewMessage(md.Output())\n")
	b.WriteString("\tif err := protojson.Unmarshal([]byte(*data), req); err != nil {\n")
	b.WriteString("\t\tlog.Fatalf(\"parse -data JSON: %v\", err)\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\tconn, err := grpc.NewClient(*addr, grpc.WithTransportCredentials(insecure.NewCredentials()))\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tlog.Fatalf(\"dial %s: %v\", *addr, err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tdefer conn.Close()\n\n")

	b.WriteString("\tctx, cancel := context.WithTimeout(context.Background(), *timeout)\n")
	b.WriteString("\tdefer cancel()\n")
	b.WriteString("\t// Send the caller's token to the server as \"authorization\" metadata; the\n")
	b.WriteString("\t// server forwards it to the upstream API, overriding its own token.\n")
	b.WriteString("\ttok := *token\n")
	b.WriteString("\tif tok == \"\" {\n")
	b.WriteString("\t\ttok = os.Getenv(\"GOOGLE_API_TOKEN\")\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif tok != \"\" {\n")
	b.WriteString("\t\tctx = metadata.AppendToOutgoingContext(ctx, \"authorization\", \"Bearer \"+tok)\n")
	b.WriteString("\t}\n")
	b.WriteString("\t// grpc.Invoke wants a leading-slash full method path.\n")
	b.WriteString("\tfullMethod := *method\n")
	b.WriteString("\tif !strings.HasPrefix(fullMethod, \"/\") {\n")
	b.WriteString("\t\tfullMethod = \"/\" + fullMethod\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := conn.Invoke(ctx, fullMethod, req, resp); err != nil {\n")
	b.WriteString("\t\tlog.Fatalf(\"call %s: %v\", fullMethod, err)\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\tout, err := protojson.MarshalOptions{Multiline: true, Indent: \"  \"}.Marshal(resp)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tlog.Fatalf(\"marshal response: %v\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tfmt.Println(string(out))\n")
	b.WriteString("}\n")

	return []byte(b.String())
}
