// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: runtime/serverconfig.proto

// Package openapi2proto.runtime holds shared types for generated servers.

package runtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerConfig is the textproto config for a generated gRPC server. It selects
// which API to serve and where to listen; it deliberately carries no
// credentials (the bearer token is read from stdin).
type ServerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API name to serve, e.g. "iam".
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// API version to serve, e.g. "v1".
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// gRPC listen address, e.g. ":50051" (defaults to ":50051" if empty).
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// Optional override for the upstream REST base URL.
	BaseUrl       string `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_runtime_serverconfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_serverconfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_runtime_serverconfig_proto_rawDescGZIP(), []int{0}
}

func (x *ServerConfig) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *ServerConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServerConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

var File_runtime_serverconfig_proto protoreflect.FileDescriptor

const file_runtime_serverconfig_proto_rawDesc = "" +
	"\n" +
	"\x1aruntime/serverconfig.proto\x12\x15openapi2proto.runtime\"o\n" +
	"\fServerConfig\x12\x10\n" +
	"\x03api\x18\x01 \x01(\tR\x03api\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrlB6Z4github.com/accretional/openapi2proto/runtime;runtimeb\x06proto3"

var (
	file_runtime_serverconfig_proto_rawDescOnce sync.Once
	file_runtime_serverconfig_proto_rawDescData []byte
)

func file_runtime_serverconfig_proto_rawDescGZIP() []byte {
	file_runtime_serverconfig_proto_rawDescOnce.Do(func() {
		file_runtime_serverconfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_serverconfig_proto_rawDesc), len(file_runtime_serverconfig_proto_rawDesc)))
	})
	return file_runtime_serverconfig_proto_rawDescData
}

var file_runtime_serverconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_runtime_serverconfig_proto_goTypes = []any{
	(*ServerConfig)(nil), // 0: openapi2proto.runtime.ServerConfig
}
var file_runtime_serverconfig_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_serverconfig_proto_init() }
func file_runtime_serverconfig_proto_init() {
	if File_runtime_serverconfig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_serverconfig_proto_rawDesc), len(file_runtime_serverconfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runtime_serverconfig_proto_goTypes,
		DependencyIndexes: file_runtime_serverconfig_proto_depIdxs,
		MessageInfos:      file_runtime_serverconfig_proto_msgTypes,
	}.Build()
	File_runtime_serverconfig_proto = out.File
	file_runtime_serverconfig_proto_goTypes = nil
	file_runtime_serverconfig_proto_depIdxs = nil
}
